genAsset:
  toItemIdentifier:
    - predicate: "tag.TSB.ID"
      to: "artifact:%%tag.TSB.ID%%"
    - predicate: "tag.TSB{Currency:1b}"
      to: "preset:currency/"
    - predicate: "tag.TSB{Currency:2b}"
      to: "preset:currency/high"
    - predicate: "tag.TSB.ShardRarity"
      to: "preset:artifact_shard/%%tag.TSB.ShardRarity%%"
    - predicate: "{}"
      to: "%%id%%"
  toItem:
    - predicate: "^artifact:(?<id>\\d)$"
      generateType: "function"
      id: "api:artifact/box/from_id"
      functionOutput:
        target: "block"
        world: "minecraft:overworld"
        x: 10000
        y: 0
        z: 10000
        path: "Items[0]"
      preCommands:
      - "data modify storage api: Argument.ID set value %%id%%"
    - predicate: "^preset:(?<id>.+)$"
      generateType: "loot_table"
      id: "%%id%%"
    - predicate: "^(?<id>.+)$"
      generateType: "give"
      id: "%%id%%"
db:
  filePath: "sqlite.db"
