asset:
  toItemIdentifier:
    - predicate: "tag.TSB.ID"
      to: "artifact:%%tag.TSB.ID%%"
    - predicate: "tag{Currency:1b}"
      to: "preset:currency/"
    - predicate: "tag{Currency:2b}"
      to: "preset:currency/high"
    - predicate: "tag.TSB.ShardRarity"
      to: "preset:sacred_shard/lv-%%tag.TSB.ShardRarity%%"
    - predicate: "{}"
      to: "%%id%%%%tag%%"
  toItem:
    - predicate: "^artifact:(?<id>\\d)$"
      generateType: "function"
      id: "api:artifact/box/from_id"
      functionOutput:
        target: "block"
        world: "minecraft:overworld"
        x: 10000
        y: 0
        z: 10000
        path: "Items[0]"
      preCommands:
      - "data modify storage api: Argument.ID set value %%id%%"
    - predicate: "^preset:(?<id>.+)$"
      generateType: "loot_table"
      id: "common:%%id%%"
    - predicate: "^(?<id>([0-9a-zA-Z_\\-.+]+:)?[0-9a-zA-Z_\\-.+]+)(?<tag>\\{.*\\})?$"
      generateType: "give"
      id: "%%id%%"
      tag: "%%tag%%"
db:
  filePath: "sqlite.db"
  attemptSaveIntervalSeconds: 30
debug: false
