name: 'LootContainerUtil'
version: '1.0.0'
main: 'com.github.chencmd.lootcontainerutil.LootContainerUtil'
api-version: '1.18'
author: 'ChenCMD'
commands:
  lcu:
    descriptions: 'loot container util'
    usage: '/lcu'
depend:
  - NBTAPI