name: 'CardGame'
version: '1.0.0'
main: 'com.github.chencmd.protectlootchest.ProtectLootChest'
api-version: '1.18'
author: 'ChenCMD'
commands:
  lcp:
    descriptions: 'loot chest protect'
    usage: '/lcp'
depend:
  - NBTAPI